### ISSUE TITLE
AccessControlException from CipherCore when Security manager enabled

### ISSUE THREAD

**Issue by enasser** [ibmruntimes/openj9-openjdk-jdk8#135]
The following test cases are failed with openssl:
com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithProviderChange.java.TestAESWithProviderChange
com/sun/crypto/provider/Cipher/AES/TestAESCiphers/TestAESWithRemoveAddProvider.java.TestAESWithRemoveAddProvider

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_security/job/openjdk8_j9_jdksecurity1test_x86-64_linux/18/

Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.action")
	at java.security.AccessController.throwACE(AccessController.java:176)
	at java.security.AccessController.checkPermissionHelper(AccessController.java:237)
	at java.security.AccessController.checkPermission(AccessController.java:373)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
	at java.lang.J9VMInternals$2.run(J9VMInternals.java:268)
	at java.security.AccessController.doPrivileged(AccessController.java:673)
	at java.lang.J9VMInternals.checkPackageAccess(J9VMInternals.java:263)
	at com.sun.crypto.provider.CipherCore.<clinit>(CipherCore.java:1231)

The issue is that from com.sun.crypto.provider.CipherCore, we are trying to access the class sun.security.action.GetPropertyAction. CipherCore is loaded with extension classloader and GetPropertyAction is loaded with boot class loader. This will result in a security exception as package.access restriction is defined in java.security. We can workaround by providing the RuntimePermission in the policy file. However, that is not a good approach as it is against the definition in java.security.. We need to read the property differently to avoid the issue..

Also, it makes more sense to have the value of jdk.nativeCrypto as 'yes' or 'no' instead of 'true' or 'false' as we need to change the default to enable native crypto when code stabilizes and then jdk.nativeCrypto=no instead of jdk.nativeCrypto=false to disable native crypto makes more sense.

**Comment by irinarada** [comment]
@enasser we need to know ASAP if this is mustfix for 0.11.0.
