### ISSUE TITLE
Update the OpenJDK exclude tests list for FIPS

### ISSUE THREAD

**Issue by WilburZjh** [ibmruntimes/openj9-openjdk-jdk8#611]
The FIPS mode has restrictive security configurations, so update the OpenJDK exclude tests list “ProblemList-fips.txt” for the FIPS testing.

**Comment by WilburZjh** [comment]
### Exclude tests list from sanity.openjdk

**java.security.NoSuchProviderException: no such provider: SunRsaSign** 

- java/math/BigInteger/ModPow65537.java.ModPow65537

**Existing Jars sign related**

- java/util/jar/JarFile/ScanSignedJar.java.ScanSignedJar
- java/util/jar/JarFile/TurkCert.java.TurkCert
- java/util/jar/JarInputStream/ScanSignedJar.java.ScanSignedJar
- java/util/jar/JarInputStream/TestIndexedJarWithBadSignature.java.TestIndexedJarWithBadSignature

**-keystore ks -storepass changeit -keypass changeit -keyalg rsa -alias a -dname CN=A -genkeypair
keytool error: java.security.KeyStoreException: 
sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ATTRIBUTE_VALUE_INVALID**

- java/util/jar/JarInputStream/ExtraFileInMetaInf.java.ExtraFileInMetaInf

**Comment by WilburZjh** [comment]
### Exclude tests list from extended.openjdk

**java.security.KeyStoreException: JCEKS not found**

- sun/security/tools/jarsigner/TsacertOptionTest.java.TsacertOptionTest

**java.security.KeyStoreException: JKS not found
java.security.NoSuchAlgorithmException: JKS KeyStore not available**

- java/security/KeyStore/CheckInputStream.java.CheckInputStream
- java/security/KeyStore/KeyStoreBuilder.java.KeyStoreBuilder
- java/security/KeyStore/PBETest.java.PBETest
- java/security/KeyStore/PKCS12/CheckDefaults.java.CheckDefaults
- java/security/KeyStore/PKCS12/WriteP12Test.java.WriteP12Test
- java/security/KeyStore/TestKeyStoreBasic.java.TestKeyStoreBasic
- java/security/KeyStore/TestKeystoreCompat.java.TestKeystoreCompat
- java/security/Policy/SignedJar/SignedJarTest.java.SignedJarTest
- javax/net/ssl/ALPN/SSLEngineAlpnTest.java.SSLEngineAlpnTest
- javax/net/ssl/ALPN/SSLServerSocketAlpnTest.java.SSLServerSocketAlpnTest
- javax/net/ssl/ALPN/SSLSocketAlpnTest.java.SSLSocketAlpnTest
- javax/net/ssl/ciphersuites/ECCurvesconstraints.java.ECCurvesconstraints
- javax/net/ssl/compatibility/ClientHelloProcessing.java.ClientHelloProcessing
- javax/net/ssl/FixingJavadocs/KMTMGetNothing.java.KMTMGetNothing
- javax/net/ssl/FixingJavadocs/SSLSessionNulls.java.SSLSessionNulls
- javax/net/ssl/interop/ClientHelloBufferUnderflowException.java.ClientHelloBufferUnderflowException
- javax/net/ssl/interop/ClientHelloChromeInterOp.java.ClientHelloChromeInterOp
- javax/net/ssl/sanity/ciphersuites/SystemPropCipherSuitesOrder.java.SystemPropCipherSuitesOrder
- javax/net/ssl/sanity/ciphersuites/TLSCipherSuitesOrder.java.TLSCipherSuitesOrder
- javax/net/ssl/sanity/interop/ClientJSSEServerJSSE.java.ClientJSSEServerJSSE
- javax/net/ssl/ServerName/SSLEngineExplorer.java.SSLEngineExplorer
- javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java.SSLEngineExplorerMatchedSNI
- javax/net/ssl/ServerName/SSLEngineExplorerUnmatchedSNI.java.SSLEngineExplorerUnmatchedSNI
- javax/net/ssl/ServerName/SSLEngineExplorerWithCli.java.SSLEngineExplorerWithCli
- javax/net/ssl/ServerName/SSLEngineExplorerWithSrv.java.SSLEngineExplorerWithSrv
- javax/net/ssl/ServerName/SSLSocketSNISensitive.java.SSLSocketSNISensitive
- javax/net/ssl/SSLEngine/ArgCheck.java.ArgCheck
- javax/net/ssl/SSLEngine/Arrays.java.Arrays
- javax/net/ssl/SSLEngine/ExtendedKeyEngine.java.ExtendedKeyEngine
- javax/net/ssl/SSLEngine/ExtendedKeySocket.java.ExtendedKeySocket
- javax/net/ssl/SSLEngine/LargeBufs.java.LargeBufs
- javax/net/ssl/SSLEngine/LargePacket.java.LargePacket
- javax/net/ssl/SSLEngine/NoAuthClientAuth.java.NoAuthClientAuth
- javax/net/ssl/SSLSession/RenegotiateTLS13.java.RenegotiateTLS13
- javax/net/ssl/SSLSession/ResumeTLS13withSNI.java.ResumeTLS13withSNI
- javax/net/ssl/SSLSession/SessionCacheSizeTests.java.SessionCacheSizeTests
- javax/net/ssl/SSLSession/SessionTimeOutTests.java.SessionTimeOutTests
- javax/net/ssl/SSLSession/SSLCtxAccessToSessCtx.java.SSLCtxAccessToSessCtx
- javax/net/ssl/SSLSession/TestEnabledProtocols.java.TestEnabledProtocols
- javax/net/ssl/SSLSocket/InputStreamClosure.java.InputStreamClosure
- javax/net/ssl/SSLSocket/OutputStreamClosure.java.OutputStreamClosure
- javax/net/ssl/SSLSocket/Tls13PacketSize.java.Tls13PacketSize
- javax/net/ssl/templates/SSLEngineTemplate.java.SSLEngineTemplate
- javax/net/ssl/templates/SSLSocketSSLEngineTemplate.java.SSLSocketSSLEngineTemplate
- javax/net/ssl/templates/SSLSocketTemplate.java.SSLSocketTemplate
- javax/net/ssl/TLS/TestJSSEClientDefaultProtocol.java.TestJSSEClientDefaultProtocol
- javax/net/ssl/TLS/TestJSSEClientProtocol.java.TestJSSEClientProtocol
- javax/net/ssl/TLS/TestJSSENoCommonProtocols.java.TestJSSENoCommonProtocols
- javax/net/ssl/TLS/TestJSSEServerProtocol.java.TestJSSEServerProtocol
- javax/net/ssl/TLS/TLSDataExchangeTest.java.TLSDataExchangeTest
- javax/net/ssl/TLS/TLSEnginesClosureTest.java.TLSEnginesClosureTest
- javax/net/ssl/TLS/TLSHandshakeTest.java.TLSHandshakeTest
- javax/net/ssl/TLS/TLSMFLNTest.java.TLSMFLNTest
- javax/net/ssl/TLS/TLSNotEnabledRC4Test.java.TLSNotEnabledRC4Test
- javax/net/ssl/TLS/TLSRehandshakeTest.java.TLSRehandshakeTest
- javax/net/ssl/TLS/TLSRehandshakeWithCipherChangeTest.java.TLSRehandshakeWithCipherChangeTest
- javax/net/ssl/TLS/TLSRehandshakeWithDataExTest.java.TLSRehandshakeWithDataExTest
- javax/net/ssl/TLS/TLSUnsupportedCiphersTest.java.TLSUnsupportedCiphersTest
- javax/net/ssl/TLSv1/TLSDataExchangeTest.java.TLSDataExchangeTest
- javax/net/ssl/TLSv1/TLSEnginesClosureTest.java.TLSEnginesClosureTest
- javax/net/ssl/TLSv1/TLSHandshakeTest.java.TLSHandshakeTest
- javax/net/ssl/TLSv1/TLSMFLNTest.java.TLSMFLNTest
- javax/net/ssl/TLSv1/TLSNotEnabledRC4Test.java.TLSNotEnabledRC4Test
- javax/net/ssl/TLSv1/TLSRehandshakeTest.java.TLSRehandshakeTest
- javax/net/ssl/TLSv1/TLSRehandshakeWithCipherChangeTest.java.TLSRehandshakeWithCipherChangeTest
- javax/net/ssl/TLSv1/TLSRehandshakeWithDataExTest.java.TLSRehandshakeWithDataExTest
- javax/net/ssl/TLSv1/TLSUnsupportedCiphersTest.java.TLSUnsupportedCiphersTest
- javax/net/ssl/TLSv11/EmptyCertificateAuthorities.java.EmptyCertificateAuthorities
- javax/net/ssl/TLSv11/TLSDataExchangeTest.java.TLSDataExchangeTest
- javax/net/ssl/TLSv11/TLSEnginesClosureTest.java.TLSEnginesClosureTest
- javax/net/ssl/TLSv11/TLSHandshakeTest.java.TLSHandshakeTest
- javax/net/ssl/TLSv11/TLSMFLNTest.java.TLSMFLNTest
- javax/net/ssl/TLSv11/TLSNotEnabledRC4Test.java.TLSNotEnabledRC4Test
- javax/net/ssl/TLSv11/TLSRehandshakeTest.java.TLSRehandshakeTest
- javax/net/ssl/TLSv11/TLSRehandshakeWithCipherChangeTest.java.TLSRehandshakeWithCipherChangeTest
- javax/net/ssl/TLSv11/TLSRehandshakeWithDataExTest.java.TLSRehandshakeWithDataExTest
- javax/net/ssl/TLSv11/TLSUnsupportedCiphersTest.java.TLSUnsupportedCiphersTest
- javax/net/ssl/TLSv12/DisabledShortDSAKeys.java.DisabledShortDSAKeys
- javax/net/ssl/TLSv12/DisabledShortRSAKeys.java.DisabledShortRSAKeys
- javax/net/ssl/TLSv12/ShortRSAKey512.java.ShortRSAKey512
- javax/net/ssl/TLSv12/ShortRSAKeyGCM.java.ShortRSAKeyGCM
- javax/net/ssl/TLSv12/SignatureAlgorithms.java.SignatureAlgorithms
- javax/net/ssl/TLSv12/TLSEnginesClosureTest.java.TLSEnginesClosureTest
- sun/security/pkcs11/rsa/TestKeyFactory.java.TestKeyFactory
- sun/security/pkcs11/rsa/TestSignatures.java.TestSignatures
- sun/security/provider/KeyStore/CaseSensitiveAliases.java.CaseSensitiveAliases
- sun/security/provider/KeyStore/TestJKSWithSecretKey.java.TestJKSWithSecretKey
- sun/security/provider/KeyStore/WrongPassword.java.WrongPassword
- sun/security/provider/X509Factory/BadPem.java.BadPem
- sun/security/provider/X509Factory/BigCRL.java.BigCRL
- sun/security/rsa/TestKeyFactory.java.TestKeyFactory
- sun/security/rsa/TestSignatures.java.TestSignatures
- sun/security/ssl/ALPN/AlpnGreaseTest.java.AlpnGreaseTest
- sun/security/ssl/CertPathRestrictions/TLSRestrictions.java.TLSRestrictions
- sun/security/ssl/ClientHandshaker/LengthCheckTest.java.LengthCheckTest
- sun/security/ssl/ClientHandshaker/RSAExport.java.RSAExport
- sun/security/ssl/DHKeyExchange/DHEKeySizing.java.DHEKeySizing
- sun/security/ssl/DHKeyExchange/UseStrongDHSizes.java.UseStrongDHSizes
- sun/security/ssl/EngineArgs/DebugReportsOneExtraByte.java.DebugReportsOneExtraByte
- sun/security/ssl/GenSSLConfigs/main.java.main
- sun/security/ssl/HandshakeOutStream/NullCerts.java.NullCerts
- sun/security/ssl/InputRecord/ClientHelloRead.java.ClientHelloRead
- sun/security/ssl/ServerHandshaker/AnonCipherWithWantClientAuth.java.AnonCipherWithWantClientAuth
- sun/security/ssl/ServerHandshaker/GetPeerHost.java.GetPeerHost
- sun/security/ssl/ServerHandshaker/HelloExtensionsTest.java.HelloExtensionsTest
- sun/security/ssl/SignatureScheme/CustomizedClientSchemes.java.CustomizedClientSchemes
- sun/security/ssl/SignatureScheme/CustomizedServerSchemes.java.CustomizedServerSchemes
- sun/security/ssl/SignatureScheme/Tls13NamedGroups.java.Tls13NamedGroups
- sun/security/ssl/SSLContextImpl/MD2InTrustAnchor.java.MD2InTrustAnchor
- sun/security/ssl/SSLContextImpl/TrustTrustedCert.java.TrustTrustedCert
- sun/security/ssl/SSLEngineImpl/CloseEngineException.java.CloseEngineException
- sun/security/ssl/SSLEngineImpl/CloseStart.java.CloseStart
- sun/security/ssl/SSLEngineImpl/DelegatedTaskWrongException.java.DelegatedTaskWrongException
- sun/security/ssl/SSLEngineImpl/EmptyExtensionData.java.EmptyExtensionData
- sun/security/ssl/SSLEngineImpl/EngineEnforceUseClientMode.java.EngineEnforceUseClientMode
- sun/security/ssl/SSLEngineImpl/RehandshakeFinished.java.RehandshakeFinished
- sun/security/ssl/SSLEngineImpl/SSLEngineBadBufferArrayAccess.java.SSLEngineBadBufferArrayAccess
- sun/security/ssl/SSLEngineImpl/SSLEngineDeadlock.java.SSLEngineDeadlock
- sun/security/ssl/SSLEngineImpl/SSLEngineFailedALPN.java.SSLEngineFailedALPN
- sun/security/ssl/SSLEngineImpl/SSLEngineKeyLimit.java.SSLEngineKeyLimit
- sun/security/ssl/SSLEngineImpl/TLS13BeginHandshake.java.TLS13BeginHandshake
- sun/security/ssl/SSLSocketImpl/ClientSocketCloseHang.java.ClientSocketCloseHang
- sun/security/ssl/SSLSocketImpl/SSLExceptionForIOIssue.java.SSLExceptionForIOIssue
- sun/security/ssl/SSLSocketImpl/SSLSocketBruceForceClose.java.SSLSocketBruceForceClose
- sun/security/ssl/SSLSocketImpl/SSLSocketClose.java.SSLSocketClose
- sun/security/ssl/SSLSocketImpl/SSLSocketKeyLimit.java.SSLSocketKeyLimit
- sun/security/ssl/X509KeyManager/CertificateAuthorities.java.CertificateAuthorities
- sun/security/ssl/X509KeyManager/PreferredKey.java.PreferredKey
- sun/security/ssl/X509KeyManager/SelectOneKeyOutOfMany.java.SelectOneKeyOutOfMany
- sun/security/ssl/X509TrustManagerImpl/BasicConstraints.java.BasicConstraints
- sun/security/ssl/X509TrustManagerImpl/CertRequestOverflow.java.CertRequestOverflow
- sun/security/ssl/X509TrustManagerImpl/CheckNullEntity.java.CheckNullEntity
- sun/security/ssl/X509TrustManagerImpl/ComodoHacker.java.ComodoHacker
- sun/security/ssl/X509TrustManagerImpl/PKIXExtendedTM.java.PKIXExtendedTM
- sun/security/ssl/X509TrustManagerImpl/SelfIssuedCert.java.SelfIssuedCert
- sun/security/ssl/X509TrustManagerImpl/SunX509ExtendedTM.java.SunX509ExtendedTM
- sun/security/ssl/X509TrustManagerImpl/TooManyCAs.java.TooManyCAs
- sun/security/ssl/X509TrustManagerImpl/X509ExtendedTMEnabled.java.X509ExtendedTMEnabled
- sun/security/tools/keytool/StartDateTest.java.StartDateTest

**Comment by WilburZjh** [comment]
detail explaination for #612

**Comment by sshuklao** [comment]
I am getting same `CKR_KEY_TYPE_INCONSISTENT` error when running Apache Spark 3.3.0 on IBM-Semeru-Runtime 11.0.16.1.
```
Caused by: java.security.InvalidKeyException: init() failed
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Mac.engineInit(P11Mac.java:208)
	at java.base/javax.crypto.Mac.chooseProvider(Mac.java:366)
	at java.base/javax.crypto.Mac.init(Mac.java:435)
	at com.ibm.stocator.thirdparty.cos.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:127)
	... 34 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_KEY_TYPE_INCONSISTENT
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_SignInit(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Mac.initialize(P11Mac.java:177)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Mac.engineInit(P11Mac.java:206)
	... 37 more
	```

**Comment by WilburZjh** [comment]
The traceStack for `javax/crypto/CipherSpi/TestGCMWithByteBuffer.java` is 
```
javax.crypto.BadPaddingException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ENCRYPTED_DATA_INVALID
	at sun.security.pkcs11.P11AEADCipher.handleException(P11AEADCipher.java:749)
	at sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:722)
	at sun.security.pkcs11.P11AEADCipher.engineDoFinal(P11AEADCipher.java:548)
	at javax.crypto.Cipher.doFinal(Cipher.java:2463)
	at TestGCMWithByteBuffer.decrypt(TestGCMWithByteBuffer.java:157)
	at TestGCMWithByteBuffer.test(TestGCMWithByteBuffer.java:86)
	at TestGCMWithByteBuffer.main(TestGCMWithByteBuffer.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:826)
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_ENCRYPTED_DATA_INVALID
	at sun.security.pkcs11.wrapper.PKCS11.C_Decrypt(Native Method)
	at sun.security.pkcs11.P11AEADCipher.implDoFinal(P11AEADCipher.java:708)
```

In NSS docs version [3.15](https://firefox-source-docs.mozilla.org/security/nss/legacy/nss_releases/nss_3.15_release_notes/index.html), it is mentioned that for Cipher mode AES-GCM.
```
PK11_Decrypt - Performs decryption as a single PKCS#11 operation (eg: not multi-part). This is necessary for AES-GCM.
PK11_Encrypt - Performs encryption as a single PKCS#11 operation (eg: not multi-part). This is necessary for AES-GCM.
```

**Comment by WilburZjh** [comment]
The traceStack for `sun/rmi/rmic/manifestClassPath/run.sh` is
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:158)
    at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:147)
    at sun.rmi.transport.LiveRef.<init>(LiveRef.java:74)
    at sun.rmi.server.UnicastServerRef.<init>(UnicastServerRef.java:168)
    at sun.rmi.server.UnicastServerRef.<init>(UnicastServerRef.java:186)
    at java.rmi.server.UnicastRemoteObject.exportObject(UnicastRemoteObject.java:301)
    at Main.main(Main.java:10)
Caused by: java.lang.RuntimeException: could not find SunPKCS11-NSS-FIPS provider for FIPS mode
    at java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:209)
    at java.security.SecureRandom.<init>(SecureRandom.java:170)
    at java.rmi.server.UID.<init>(UID.java:112)
    at java.rmi.server.ObjID.<clinit>(ObjID.java:88)
    ... 5 more
```
If we assign a directory to `-Djava.ext.dirs` jvm options, the `ExtClassLoader` will not load the jar file under `${JAVA_HOME}/jre/lib/ext`. Therefore, this is not a FIPS relavant problem.

One solution that fix this issue is expanding -Djava.ext.dirs with {JAVA_HOME}/jre/lib/ext.

**Comment by WilburZjh** [comment]
**sun.security.pkcs11.wrapper.PKCS11Exception: CKR_KEY_SIZE_RANGE
The minimum length for an MD5 HMAC key is 16 bytes.
However, this test uses a 4 bytes length key for HmacMD5.**
com/sun/crypto/provider/Mac/HmacMD5.java.HmacMD5
